In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/ilc_di03_linear_2_0.csv")
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,age,Age class,sex,Sex,statinfo,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2017,NaN,2122,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2018,NaN,2310,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2019,NaN,2574,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2020,NaN,2909,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2021,NaN,2971,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(331404, 23)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 331404 entries, 0 to 331403
Data columns (total 23 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   STRUCTURE                               331404 non-null  str
 1   STRUCTURE_ID                            331404 non-null  str
 2   STRUCTURE_NAME                          331404 non-null  str
 3   freq                                    331404 non-null  str
 4   Time frequency                          331404 non-null  str
 5   age                                     331404 non-null  str
 6   Age class                               331404 non-null  str
 7   sex                                     331404 non-null  str
 8   Sex                                     331404 non-null  str
 9   statinfo                                331404 non-null  str
 10  Statistical information                 331404 non-null  str
 11  unit                                    331404 non-null  str
 12  Unit of measure                         331404 non-null  str
 13  geo                                     331404 non-null  str
 14  Geopolitical entity (reporting)         331404 non-null  str
 15  TIME_PERIOD                             331404 non-null  int64
 16  Time                                    0 non-null       float64
 17  OBS_VALUE                               331404 non-null  int64
 18  Observation value                       0 non-null       float64
 19  OBS_FLAG                                25164 non-null   str
 20  Observation status (Flag) V2 structure  25164 non-null   str
 21  CONF_STATUS                             0 non-null       float64
 22  Confidentiality status (flag)           0 non-null       float64
dtypes: float64(4), int64(2), str(17)
memory usage: 58.2 MB

In [5]:
df.describe()

,TIME_PERIOD,Time,OBS_VALUE,Observation value,CONF_STATUS,Confidentiality status (flag)
count,331404.000000,0.0,3.314040e+05,0.0,0.0,0.0
mean,2013.656643,NaN,7.125268e+04,NaN,NaN,NaN
std,7.405403,NaN,3.632968e+05,NaN,NaN,NaN
min,1995.000000,NaN,9.860000e+02,NaN,NaN,NaN
25%,2008.000000,NaN,9.815000e+03,NaN,NaN,NaN
50%,2014.000000,NaN,1.666000e+04,NaN,NaN,NaN
75%,2020.000000,NaN,2.351900e+04,NaN,NaN,NaN
max,2025.000000,NaN,6.386511e+06,NaN,NaN,NaN

In [6]:
for column in ["age", "sex", "statinfo", "unit", "geo", "TIME_PERIOD"]:
    print(column, ":", sorted(df[column].unique().tolist()))

age : ['TOTAL', 'Y11-15', 'Y12-17', 'Y16-24', 'Y16-64', 'Y18-24', 'Y18-64', 'Y25-49', 'Y25-54', 'Y50-64', 'Y55-64', 'Y6-10', 'Y6-11', 'Y65-74', 'Y_GE16', 'Y_GE18', 'Y_GE60', 'Y_GE65', 'Y_GE75', 'Y_LT16', 'Y_LT18', 'Y_LT6', 'Y_LT60', 'Y_LT65', 'Y_LT75']
sex : ['F', 'M', 'T']
statinfo : ['MEAN_EI', 'MED_EI']
unit : ['EUR', 'NAC', 'PPS']
geo : ['AL', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EA', 'EA18', 'EA19', 'EA20', 'EA21', 'EE', 'EL', 'ES', 'EU', 'EU15', 'EU27_2007', 'EU27_2020', 'EU28', 'FI', 'FR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'TR', 'UK', 'XK']
TIME_PERIOD : [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [7]:
df[["OBS_FLAG", "Observation status (Flag) V2 structure"]].value_counts(dropna=False)

OBS_FLAG  Observation status (Flag) V2 structure
NaN       NaN                                       306240
b         break in time series                       18216
e         estimated                                   6144
p         provisional                                  792
u         low reliability                               12
Name: count, dtype: int64

In [9]:
df_clean = df.dropna(axis=1, how="all")
df_clean = df_clean.drop(columns=[
    "STRUCTURE", "STRUCTURE_ID", "STRUCTURE_NAME", "freq", "Time frequency"])
df_clean.shape

(331404, 14)

In [10]:
age_groups = {
    "Y_LT18": "0–17",
    "Y18-24": "18–24",
    "Y25-49": "25–49",
    "Y50-64": "50–64",
    "Y_GE65": "65+"}

df_age = df_clean[df_clean["age"].isin(age_groups)].copy()
df_age["age_group"] = df_age["age"].map(age_groups)
df_age["age_group"].value_counts().sort_index()

age_group
0–17     13902
18–24    13902
25–49    15606
50–64    15606
65+      15606
Name: count, dtype: int64

In [11]:
column_names = {
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "statinfo": "indicator",
    "OBS_VALUE": "income",
    "OBS_FLAG": "obs_flag"}

df_clean = df_clean.rename(columns=column_names)
df_age = df_age.rename(columns=column_names)
df_age.head()

,age,Age class,sex,Sex,indicator,Statistical information,unit,Unit of measure,geo_code,geo_name,year,income,obs_flag,Observation status (Flag) V2 structure,age_group
62424,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2017,2042,NaN,NaN,18–24
62425,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2018,2168,NaN,NaN,18–24
62426,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2019,2438,NaN,NaN,18–24
62427,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2020,2821,NaN,NaN,18–24
62428,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2021,2890,NaN,NaN,18–24

In [12]:
df_age.info()

<class 'pandas.DataFrame'>
Index: 74622 entries, 62424 to 270683
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   age                                     74622 non-null  str
 1   Age class                               74622 non-null  str
 2   sex                                     74622 non-null  str
 3   Sex                                     74622 non-null  str
 4   indicator                               74622 non-null  str
 5   Statistical information                 74622 non-null  str
 6   unit                                    74622 non-null  str
 7   Unit of measure                         74622 non-null  str
 8   geo_code                                74622 non-null  str
 9   geo_name                                74622 non-null  str
 10  year                                    74622 non-null  int64
 11  income                                  74622 non-null  int64
 12  obs_flag                                5682 non-null   str
 13  Observation status (Flag) V2 structure  5682 non-null   str
 14  age_group                               74622 non-null  str
dtypes: int64(2), str(13)
memory usage: 9.1 MB

In [13]:
columns = ["geo_code", "geo_name", "year", "age", "age_group", "sex", "indicator", "unit", "income", "obs_flag"]
df_age = df_age[columns].copy()

df_age["age_group"] = pd.Categorical(
    df_age["age_group"],
    categories=list(age_groups.values()),
    ordered=True)
df_age.info()

<class 'pandas.DataFrame'>
Index: 74622 entries, 62424 to 270683
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   geo_code   74622 non-null  str
 1   geo_name   74622 non-null  str
 2   year       74622 non-null  int64
 3   age        74622 non-null  str
 4   age_group  74622 non-null  category
 5   sex        74622 non-null  str
 6   indicator  74622 non-null  str
 7   unit       74622 non-null  str
 8   income     74622 non-null  int64
 9   obs_flag   5682 non-null   str
dtypes: category(1), int64(2), str(7)
memory usage: 5.8 MB

### Analysis period

The analysis covers survey years 2003–2025. We start in 2003 because it is the first year in the CSV with all five selected age groups. The period ends in 2025, the latest available year. Country coverage and breaks in series are assessed separately before comparisons.

In [14]:
df_clean = df_clean[df_clean["year"].between(2003, 2025)].copy()
df_age = df_age[df_age["year"].between(2003, 2025)].copy()

df_clean.shape, df_age.shape

((305844, 14), (69510, 10))

In [20]:
df_clean = df_clean.loc[df_clean["sex"].eq("T")].copy()
df_age = df_age.loc[df_age["sex"].eq("T")].copy()

country_data = df_age.loc[~df_age["geo_code"].str.startswith(("EU", "EA"))].copy()

df_clean.shape, df_age.shape

((101948, 14), (23170, 10))

In [21]:
coverage = (
    country_data.groupby(["geo_code", "geo_name"])["year"]
    .agg(
        first_year="min",
        last_year="max",
        years_available="nunique").reset_index())

In [22]:
coverage["years_missing"] = 23 - coverage["years_available"]
coverage.sort_values(["years_available", "geo_name"], ascending=[False, True])

,geo_code,geo_name,first_year,last_year,years_available,years_missing
1,AT,Austria,2003,2025,23,0
2,BE,Belgium,2003,2025,23,0
8,DK,Denmark,2003,2025,23,0
10,EL,Greece,2003,2025,23,0
16,IE,Ireland,2003,2025,23,0
20,LU,Luxembourg,2003,2025,23,0
26,NO,Norway,2003,2025,23,0
9,EE,Estonia,2004,2025,22,1
12,FI,Finland,2004,2025,22,1
13,FR,France,2004,2025,22,1
18,IT,Italy,2004,2025,22,1
28,PT,Portugal,2004,2025,22,1
11,ES,Spain,2004,2025,22,1
31,SE,Sweden,2004,2025,22,1
5,CY,Cyprus,2005,2025,21,2
6,CZ,Czechia,2005,2025,21,2
7,DE,Germany,2005,2025,21,2
15,HU,Hungary,2005,2025,21,2
21,LV,Latvia,2005,2025,21,2
19,LT,Lithuania,2005,2025,21,2
24,MT,Malta,2005,2025,21,2
25,NL,Netherlands,2005,2025,21,2
27,PL,Poland,2005,2025,21,2
33,SK,Slovakia,2005,2025,21,2
32,SI,Slovenia,2005,2025,21,2
3,BG,Bulgaria,2006,2025,20,3
34,TR,Türkiye,2006,2025,20,3
29,RO,Romania,2007,2025,19,4
4,CH,Switzerland,2007,2024,18,5
17,IS,Iceland,2004,2020,17,6
14,HR,Croatia,2010,2025,16,7
35,UK,United Kingdom,2005,2018,14,9
23,MK,North Macedonia,2012,2024,13,10
30,RS,Serbia,2013,2025,13,10
22,ME,Montenegro,2013,2024,12,11
0,AL,Albania,2017,2025,9,14
36,XK,Kosovo*,2018,2018,1,22

In [23]:
flag_summary = (
    country_data[country_data["obs_flag"].notna()]
    .groupby(["geo_code", "geo_name", "year", "obs_flag"])
    .size()
    .reset_index(name="observations"))

flag_summary.sort_values(["geo_name", "year"])

   geo_code         geo_name  year obs_flag  observations
0        AT          Austria  2003        b            30
1        AT          Austria  2008        b            30
2        BE          Belgium  2003        b            30
3        BE          Belgium  2019        b            30
4        BG         Bulgaria  2016        b            30
20       HR          Croatia  2023        b            30
21       HR          Croatia  2024        b            30
6        CY           Cyprus  2008        b            30
9        DK          Denmark  2011        b            30
10       DK          Denmark  2020        b            30
11       EE          Estonia  2014        b            30
15       FI          Finland  2004        b            30
16       FR           France  2004        b            30
17       FR           France  2008        b            30
18       FR           France  2020        b            30
19       FR           France  2022        b            30
7        DE          Germany  2005        b            30
8        DE          Germany  2020        b            30
12       EL           Greece  2003        b            30
22       HU          Hungary  2019        b            30
23       IE          Ireland  2003        b            30
24       IE          Ireland  2019        b            30
25       IE          Ireland  2020        b            30
26       IT            Italy  2004        b            30
27       LT        Lithuania  2024        p            30
28       LT        Lithuania  2025        p            30
29       LU       Luxembourg  2003        b            30
30       LU       Luxembourg  2016        b            30
31       LU       Luxembourg  2020        b            30
32       LU       Luxembourg  2021        b            30
33       LU       Luxembourg  2022        b            30
34       LU       Luxembourg  2025        b            30
36       NL      Netherlands  2005        b            30
37       NL      Netherlands  2016        b            30
35       MK  North Macedonia  2021        b            30
38       NO           Norway  2021        b            30
39       NO           Norway  2023        b            30
40       PT         Portugal  2004        b            30
42       SK         Slovakia  2025        b            30
13       ES            Spain  2004        b            30
14       ES            Spain  2008        b            30
41       SE           Sweden  2008        b            30
5        CH      Switzerland  2014        b            30
43       UK   United Kingdom  2005        b            30
44       UK   United Kingdom  2012        b            30
45       UK   United Kingdom  2017        b            30

In [24]:
combination_counts = (
    country_data.groupby(["geo_code", "geo_name", "year"])
    .size()
    .reset_index(name="observations"))

combination_counts["observations"].value_counts().sort_index()

observations
30    718
Name: count, dtype: int64

In [25]:
df_clean.to_csv("../data/processed/ilc_di03_clean.csv", index=False, encoding="utf-8")

In [26]:
df_age.to_csv("../data/processed/ilc_di03_age_groups.csv", index=False, encoding="utf-8")

### Preparation summary

We checked the file, country/year coverage, flags and duplicate keys, removed unused columns, and kept survey years **2003–2025** with `sex = T`. A separate table contains the age groups **0–17, 18–24, 25–49, 50–64 and 65+**.

Both tables are saved in `data/processed/`. We will use the next notebook for the main analysis, visualisations and interpretation of the results.