In [68]:
import pandas as pd

In [69]:
df = pd.read_csv("../data/raw/ilc_di03_linear_2_0.csv")
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,age,Age class,sex,Sex,statinfo,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2017,NaN,2122,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2018,NaN,2310,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2019,NaN,2574,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2020,NaN,2909,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ILC_DI03(1.0),Mean and median income by age and sex,A,Annual,TOTAL,Total,F,Females,MEAN_EI,...,AL,Albania,2021,NaN,2971,NaN,NaN,NaN,NaN,NaN

In [70]:
df.shape

(331404, 23)

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 331404 entries, 0 to 331403
Data columns (total 23 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   STRUCTURE                               331404 non-null  str
 1   STRUCTURE_ID                            331404 non-null  str
 2   STRUCTURE_NAME                          331404 non-null  str
 3   freq                                    331404 non-null  str
 4   Time frequency                          331404 non-null  str
 5   age                                     331404 non-null  str
 6   Age class                               331404 non-null  str
 7   sex                                     331404 non-null  str
 8   Sex                                     331404 non-null  str
 9   statinfo                                331404 non-null  str
 10  Statistical information                 331404 non-null  str
 11  unit                                    331404 non-null  str
 12  Unit of measure                         331404 non-null  str
 13  geo                                     331404 non-null  str
 14  Geopolitical entity (reporting)         331404 non-null  str
 15  TIME_PERIOD                             331404 non-null  int64
 16  Time                                    0 non-null       float64
 17  OBS_VALUE                               331404 non-null  int64
 18  Observation value                       0 non-null       float64
 19  OBS_FLAG                                25164 non-null   str
 20  Observation status (Flag) V2 structure  25164 non-null   str
 21  CONF_STATUS                             0 non-null       float64
 22  Confidentiality status (flag)           0 non-null       float64
dtypes: float64(4), int64(2), str(17)
memory usage: 58.2 MB

In [72]:
df.describe()

,TIME_PERIOD,Time,OBS_VALUE,Observation value,CONF_STATUS,Confidentiality status (flag)
count,331404.000000,0.0,3.314040e+05,0.0,0.0,0.0
mean,2013.656643,NaN,7.125268e+04,NaN,NaN,NaN
std,7.405403,NaN,3.632968e+05,NaN,NaN,NaN
min,1995.000000,NaN,9.860000e+02,NaN,NaN,NaN
25%,2008.000000,NaN,9.815000e+03,NaN,NaN,NaN
50%,2014.000000,NaN,1.666000e+04,NaN,NaN,NaN
75%,2020.000000,NaN,2.351900e+04,NaN,NaN,NaN
max,2025.000000,NaN,6.386511e+06,NaN,NaN,NaN

In [73]:
for column in ["age", "sex", "statinfo", "unit", "geo", "TIME_PERIOD"]:
    print(column, ":", sorted(df[column].unique().tolist()))

age : ['TOTAL', 'Y11-15', 'Y12-17', 'Y16-24', 'Y16-64', 'Y18-24', 'Y18-64', 'Y25-49', 'Y25-54', 'Y50-64', 'Y55-64', 'Y6-10', 'Y6-11', 'Y65-74', 'Y_GE16', 'Y_GE18', 'Y_GE60', 'Y_GE65', 'Y_GE75', 'Y_LT16', 'Y_LT18', 'Y_LT6', 'Y_LT60', 'Y_LT65', 'Y_LT75']

sex : ['F', 'M', 'T']
statinfo : ['MEAN_EI', 'MED_EI']
unit : ['EUR', 'NAC', 'PPS']
geo : ['AL', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EA', 'EA18', 'EA19', 'EA20', 'EA21', 'EE', 'EL', 'ES', 'EU', 'EU15', 'EU27_2007', 'EU27_2020', 'EU28', 'FI', 'FR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'TR', 'UK', 'XK']
TIME_PERIOD : [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [74]:
df[["OBS_FLAG", "Observation status (Flag) V2 structure"]].value_counts(dropna=False)

OBS_FLAG  Observation status (Flag) V2 structure
NaN       NaN                                       306240
b         break in time series                       18216
e         estimated                                   6144
p         provisional                                  792
u         low reliability                               12
Name: count, dtype: int64

In [75]:
df_clean = df.dropna(axis=1, how="all")
df_clean = df_clean.drop(columns=[
    "STRUCTURE", "STRUCTURE_ID", "STRUCTURE_NAME", "freq", "Time frequency"])
df_clean.shape

(331404, 14)

In [76]:
age_groups = {
    "Y_LT18": "0–17",
    "Y18-24": "18–24",
    "Y25-49": "25–49",
    "Y50-64": "50–64",
    "Y_GE65": "65+"}

df_age = df_clean[df_clean["age"].isin(age_groups)].copy()
df_age["age_group"] = df_age["age"].map(age_groups)
df_age["age_group"].value_counts().sort_index()

age_group
0–17     13902
18–24    13902
25–49    15606
50–64    15606
65+      15606
Name: count, dtype: int64

In [77]:
column_names = {
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "statinfo": "indicator",
    "OBS_VALUE": "income",
    "OBS_FLAG": "obs_flag"}

df_clean = df_clean.rename(columns=column_names)
df_age = df_age.rename(columns=column_names)
df_age.head()

,age,Age class,sex,Sex,indicator,Statistical information,unit,Unit of measure,geo_code,geo_name,year,income,obs_flag,Observation status (Flag) V2 structure,age_group
62424,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2017,2042,NaN,NaN,18–24
62425,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2018,2168,NaN,NaN,18–24
62426,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2019,2438,NaN,NaN,18–24
62427,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2020,2821,NaN,NaN,18–24
62428,Y18-24,From 18 to 24 years,F,Females,MEAN_EI,Mean equivalised income,EUR,Euro,AL,Albania,2021,2890,NaN,NaN,18–24

In [78]:
df_age.info()

<class 'pandas.DataFrame'>
Index: 74622 entries, 62424 to 270683
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   age                                     74622 non-null  str
 1   Age class                               74622 non-null  str
 2   sex                                     74622 non-null  str
 3   Sex                                     74622 non-null  str
 4   indicator                               74622 non-null  str
 5   Statistical information                 74622 non-null  str
 6   unit                                    74622 non-null  str
 7   Unit of measure                         74622 non-null  str
 8   geo_code                                74622 non-null  str
 9   geo_name                                74622 non-null  str
 10  year                                    74622 non-null  int64
 11  income                                  74622 non-null  int64
 12  obs_flag                                5682 non-null   str
 13  Observation status (Flag) V2 structure  5682 non-null   str
 14  age_group                               74622 non-null  str
dtypes: int64(2), str(13)
memory usage: 9.1 MB

In [79]:
columns = ["geo_code", "geo_name", "year", "age", "age_group", "sex", "indicator", "unit", "income", "obs_flag"]
df_age = df_age[columns].copy()

df_age["age_group"] = pd.Categorical(
    df_age["age_group"],
    categories=list(age_groups.values()),
    ordered=True)
df_age.info()

<class 'pandas.DataFrame'>
Index: 74622 entries, 62424 to 270683
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   geo_code   74622 non-null  str
 1   geo_name   74622 non-null  str
 2   year       74622 non-null  int64
 3   age        74622 non-null  str
 4   age_group  74622 non-null  category
 5   sex        74622 non-null  str
 6   indicator  74622 non-null  str
 7   unit       74622 non-null  str
 8   income     74622 non-null  int64
 9   obs_flag   5682 non-null   str
dtypes: category(1), int64(2), str(7)
memory usage: 5.8 MB

### Analysis period

The analysis covers survey years 2003–2025. We start in 2003 because it is the first year in the CSV with all five selected age groups. The period ends in 2025, the latest available year. Country coverage and breaks in series are assessed separately before comparisons.

In [80]:
df_clean = df_clean[df_clean["year"].between(2003, 2025)].copy()
df_age = df_age[df_age["year"].between(2003, 2025)].copy()

df_clean.shape, df_age.shape

((305844, 14), (69510, 10))

In [81]:
df_clean = df_clean.loc[df_clean["sex"].eq("T")].copy()
df_age = df_age.loc[df_age["sex"].eq("T")].copy()

country_data = df_age.loc[~df_age["geo_code"].str.startswith(("EU", "EA"))].copy()

df_clean.shape, df_age.shape

((101948, 14), (23170, 10))

In [82]:
coverage = (
    country_data.groupby(["geo_code", "geo_name"])["year"]
    .agg(
        first_year="min",
        last_year="max",
        years_available="nunique").reset_index())

In [83]:
coverage["years_missing"] = 23 - coverage["years_available"]
coverage.sort_values(["years_available", "geo_name"], ascending=[False, True])

,geo_code,geo_name,first_year,last_year,years_available,years_missing
1,AT,Austria,2003,2025,23,0
2,BE,Belgium,2003,2025,23,0
8,DK,Denmark,2003,2025,23,0
10,EL,Greece,2003,2025,23,0
16,IE,Ireland,2003,2025,23,0
20,LU,Luxembourg,2003,2025,23,0
26,NO,Norway,2003,2025,23,0
9,EE,Estonia,2004,2025,22,1
12,FI,Finland,2004,2025,22,1
13,FR,France,2004,2025,22,1
18,IT,Italy,2004,2025,22,1
28,PT,Portugal,2004,2025,22,1
11,ES,Spain,2004,2025,22,1
31,SE,Sweden,2004,2025,22,1
5,CY,Cyprus,2005,2025,21,2
6,CZ,Czechia,2005,2025,21,2
7,DE,Germany,2005,2025,21,2
15,HU,Hungary,2005,2025,21,2
21,LV,Latvia,2005,2025,21,2
19,LT,Lithuania,2005,2025,21,2
24,MT,Malta,2005,2025,21,2
25,NL,Netherlands,2005,2025,21,2
27,PL,Poland,2005,2025,21,2
33,SK,Slovakia,2005,2025,21,2
32,SI,Slovenia,2005,2025,21,2
3,BG,Bulgaria,2006,2025,20,3
34,TR,Türkiye,2006,2025,20,3
29,RO,Romania,2007,2025,19,4
4,CH,Switzerland,2007,2024,18,5
17,IS,Iceland,2004,2020,17,6
14,HR,Croatia,2010,2025,16,7
35,UK,United Kingdom,2005,2018,14,9
23,MK,North Macedonia,2012,2024,13,10
30,RS,Serbia,2013,2025,13,10
22,ME,Montenegro,2013,2024,12,11
0,AL,Albania,2017,2025,9,14
36,XK,Kosovo*,2018,2018,1,22

In [84]:
flag_summary = (
    country_data[country_data["obs_flag"].notna()]
    .groupby(["geo_code", "geo_name", "year", "obs_flag"])
    .size()
    .reset_index(name="observations"))

flag_summary.sort_values(["geo_name", "year"])

   geo_code         geo_name  year obs_flag  observations
0        AT          Austria  2003        b            30
1        AT          Austria  2008        b            30
2        BE          Belgium  2003        b            30
3        BE          Belgium  2019        b            30
4        BG         Bulgaria  2016        b            30
20       HR          Croatia  2023        b            30
21       HR          Croatia  2024        b            30
6        CY           Cyprus  2008        b            30
9        DK          Denmark  2011        b            30
10       DK          Denmark  2020        b            30
11       EE          Estonia  2014        b            30
15       FI          Finland  2004        b            30
16       FR           France  2004        b            30
17       FR           France  2008        b            30
18       FR           France  2020        b            30
19       FR           France  2022        b            30
7        DE          Germany  2005        b            30
8        DE          Germany  2020        b            30
12       EL           Greece  2003        b            30
22       HU          Hungary  2019        b            30
23       IE          Ireland  2003        b            30
24       IE          Ireland  2019        b            30
25       IE          Ireland  2020        b            30
26       IT            Italy  2004        b            30
27       LT        Lithuania  2024        p            30
28       LT        Lithuania  2025        p            30
29       LU       Luxembourg  2003        b            30
30       LU       Luxembourg  2016        b            30
31       LU       Luxembourg  2020        b            30
32       LU       Luxembourg  2021        b            30
33       LU       Luxembourg  2022        b            30
34       LU       Luxembourg  2025        b            30
36       NL      Netherlands  2005        b            30
37       NL      Netherlands  2016        b            30
35       MK  North Macedonia  2021        b            30
38       NO           Norway  2021        b            30
39       NO           Norway  2023        b            30
40       PT         Portugal  2004        b            30
42       SK         Slovakia  2025        b            30
13       ES            Spain  2004        b            30
14       ES            Spain  2008        b            30
41       SE           Sweden  2008        b            30
5        CH      Switzerland  2014        b            30
43       UK   United Kingdom  2005        b            30
44       UK   United Kingdom  2012        b            30
45       UK   United Kingdom  2017        b            30

In [85]:
combination_counts = (
    country_data.groupby(["geo_code", "geo_name", "year"])
    .size()
    .reset_index(name="observations"))

combination_counts["observations"].value_counts().sort_index()

observations
30    718
Name: count, dtype: int64

In [86]:
key = ["geo_code", "year", "age", "sex", "indicator", "unit"]

print("Duplicate income keys:", df_clean.duplicated(key).sum())
print("Duplicate age-group keys:", df_age.duplicated(key).sum())

Duplicate income keys: 0
Duplicate age-group keys: 0

In [87]:
df_clean.to_csv("../data/processed/ilc_di03_clean.csv", index=False, encoding="utf-8")

In [88]:
df_age.to_csv("../data/processed/ilc_di03_age_groups.csv", index=False, encoding="utf-8")

### Income data preparation summary

We checked the file, country/year coverage, flags and duplicate keys, removed unused columns, and kept survey years **2003–2025** with `sex = T`. A separate table contains the age groups **0–17, 18–24, 25–49, 50–64 and 65+**.

Both tables are saved in `data/processed/`. We will use the next notebook for the main analysis, visualisations and interpretation of the results.

### HICP data preparation

In [89]:
hicp_raw = pd.read_csv("../data/raw/prc_hicp_ainr__custom_23673998_linear_2_0.csv")

In [90]:
display(hicp_raw[["STRUCTURE_ID", "freq", "unit", "coicop18"]].drop_duplicates())

                  STRUCTURE_ID freq       unit coicop18
0     ESTAT:PRC_HICP_AINR(1.0)    A  INX_A_AVG    TOTAL
1189  ESTAT:PRC_HICP_AINR(1.0)    A  RCH_A_AVG    TOTAL

In [91]:
hicp_greece = hicp_raw.loc[
    (hicp_raw["geo"] == "EL")
    & (hicp_raw["freq"] == "A")
    & (hicp_raw["unit"] == "INX_A_AVG")
    & (hicp_raw["coicop18"] == "TOTAL")
    & hicp_raw["TIME_PERIOD"].between(2002, 2024),
    ["TIME_PERIOD", "OBS_VALUE", "OBS_FLAG"],
].copy()

In [92]:
print("Column types:")
print(hicp_greece.dtypes)

print("Missing index values:", hicp_greece["OBS_VALUE"].isna().sum())
print("Duplicate years:", hicp_greece["TIME_PERIOD"].duplicated().sum())

display(hicp_greece.sort_values("TIME_PERIOD"))

Column types:
TIME_PERIOD      int64
OBS_VALUE      float64
OBS_FLAG       float64
dtype: object
Missing index values: 0
Duplicate years: 0

     TIME_PERIOD  OBS_VALUE  OBS_FLAG
397         2002      62.30       NaN
398         2003      64.45       NaN
399         2004      66.40       NaN
400         2005      68.72       NaN
401         2006      70.99       NaN
402         2007      73.11       NaN
403         2008      76.21       NaN
404         2009      77.24       NaN
405         2010      80.87       NaN
406         2011      83.39       NaN
407         2012      84.25       NaN
408         2013      83.53       NaN
409         2014      82.37       NaN
410         2015      81.46       NaN
411         2016      81.48       NaN
412         2017      82.40       NaN
413         2018      83.04       NaN
414         2019      83.47       NaN
415         2020      82.42       NaN
416         2021      82.89       NaN
417         2022      90.60       NaN
418         2023      94.37       NaN
419         2024      97.19       NaN

In [93]:
hicp_greece.to_csv("../data/processed/hicp_greece.csv", index=False, encoding="utf-8")

### Housing data preparation

In [94]:
housing_raw = pd.read_csv("../data/raw/ilc_lvho07a_linear_2_0.csv")

print("Raw shape:", housing_raw.shape)
display(housing_raw[["STRUCTURE_ID", "freq", "unit"]].drop_duplicates())

Raw shape: (126729, 23)

             STRUCTURE_ID freq unit
0  ESTAT:ILC_LVHO07A(1.0)    A   PC

In [95]:
# Inspect the Greek observations before selecting population groups.
housing_greece = housing_raw.loc[housing_raw["geo"] == "EL"].copy()

print("Available years:", sorted(housing_greece["TIME_PERIOD"].unique()))

display(housing_greece[["rskpovth", "Risk of poverty threshold"]].drop_duplicates())
display(housing_greece[["age", "Age class"]].drop_duplicates())
display(housing_greece[["sex", "Sex"]].drop_duplicates())

print("Column types:")
print(housing_greece[["TIME_PERIOD", "OBS_VALUE", "OBS_FLAG"]].dtypes)

print("Missing values:", housing_greece["OBS_VALUE"].isna().sum())

housing_key = ["freq", "unit", "rskpovth", "age", "sex", "geo", "TIME_PERIOD"]
print("Duplicate observation keys:", housing_greece.duplicated(housing_key).sum())

display(housing_greece[["OBS_FLAG", "Observation status (Flag) V2 structure"]].value_counts(dropna=False))

Available years: [np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

      rskpovth Risk of poverty threshold
262       A_60                 Above 60%
42505     B_60                 Below 60%
84748    TOTAL                     Total

          age            Age class
262     TOTAL                Total
2755   Y12-17  From 12 to 17 years
5248   Y15-19  From 15 to 19 years
7723   Y15-24  From 15 to 24 years
10198  Y15-29  From 15 to 29 years
12673  Y16-19  From 16 to 19 years
15148  Y16-24  From 16 to 24 years
17623  Y16-29  From 16 to 29 years
20098  Y18-24  From 18 to 24 years
22591  Y18-64  From 18 to 64 years
25084  Y20-24  From 20 to 24 years
27562  Y20-29  From 20 to 29 years
30040  Y25-29  From 25 to 29 years
32533   Y6-11   From 6 to 11 years
35026  Y_GE65     65 years or over
37519  Y_LT18   Less than 18 years
40012   Y_LT6    Less than 6 years

     sex      Sex
262    F  Females
1093   M    Males
1924   T    Total

Column types:
TIME_PERIOD      int64
OBS_VALUE      float64
OBS_FLAG           str
dtype: object
Missing values: 0
Duplicate observation keys: 0

OBS_FLAG  Observation status (Flag) V2 structure
NaN       NaN                                       3365
u         low reliability                              1
Name: count, dtype: int64

In [96]:
# Identify the flagged observation before filtering by sex.
display(housing_greece.loc[housing_greece["OBS_FLAG"].notna(), ["TIME_PERIOD", "age", "sex", "rskpovth", "OBS_VALUE", "OBS_FLAG"]])

       TIME_PERIOD     age sex rskpovth  OBS_VALUE OBS_FLAG
72304         2025  Y25-29   F     B_60       74.8        u

In [97]:
# Keep all available age and poverty-status groups for the total population.
housing_clean = housing_greece.loc[
    housing_greece["sex"] == "T",
    [   "geo", "Geopolitical entity (reporting)", "TIME_PERIOD",
        "age", "Age class", "sex",
        "rskpovth", "Risk of poverty threshold",
        "unit", "OBS_VALUE", "OBS_FLAG"]].copy()

housing_clean = housing_clean.rename(columns={
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "housing_overburden_rate",
    "OBS_FLAG": "obs_flag"})

housing_clean = housing_clean.sort_values(["rskpovth", "age", "year"])

print("Prepared shape:", housing_clean.shape)
display(housing_clean.head())

Prepared shape: (1122, 11)

,geo_code,geo_name,year,age,Age class,sex,rskpovth,Risk of poverty threshold,unit,housing_overburden_rate,obs_flag
1924,EL,Greece,2004,TOTAL,Total,T,A_60,Above 60%,PC,13.2,NaN
1925,EL,Greece,2005,TOTAL,Total,T,A_60,Above 60%,PC,12.2,NaN
1926,EL,Greece,2006,TOTAL,Total,T,A_60,Above 60%,PC,13.3,NaN
1927,EL,Greece,2007,TOTAL,Total,T,A_60,Above 60%,PC,3.2,NaN
1928,EL,Greece,2008,TOTAL,Total,T,A_60,Above 60%,PC,11.3,NaN

In [98]:
# Save the prepared data with observation flags.
housing_clean.to_csv("../data/processed/ilc_lvho07a_greece.csv", index=False, encoding="utf-8")

### Income by degree of urbanisation

In [99]:
urban_raw = pd.read_csv("../data/raw/ilc_di17_linear_2_0.csv")

print("Raw shape:", urban_raw.shape)
display(urban_raw[["STRUCTURE_ID", "freq", "unit", "statinfo"]].drop_duplicates())

Raw shape: (286578, 25)

               STRUCTURE_ID freq unit statinfo
0       ESTAT:ILC_DI17(1.0)    A  EUR  MEAN_EI
49296   ESTAT:ILC_DI17(1.0)    A  EUR   MED_EI
98592   ESTAT:ILC_DI17(1.0)    A  NAC  MEAN_EI
143289  ESTAT:ILC_DI17(1.0)    A  NAC   MED_EI
187986  ESTAT:ILC_DI17(1.0)    A  PPS  MEAN_EI
237282  ESTAT:ILC_DI17(1.0)    A  PPS   MED_EI

In [100]:
# Inspect the Greek observations before selecting analysis groups.
urban_greece = urban_raw.loc[urban_raw["geo"] == "EL"].copy()

print("Available years:", sorted(urban_greece["TIME_PERIOD"].unique().tolist()))

display(urban_greece[["deg_urb", "Degree of urbanisation"]].drop_duplicates())
display(urban_greece[["age", "Age class", "sex", "Sex"]].drop_duplicates())

print("Column types:")
print(urban_greece[["TIME_PERIOD", "OBS_VALUE", "OBS_FLAG"]].dtypes)

print("Missing values:", urban_greece["OBS_VALUE"].isna().sum())

urban_key = ["freq", "unit", "statinfo", "deg_urb", "sex", "age", "geo", "TIME_PERIOD"]
print("Duplicate observation keys:", urban_greece.duplicated(urban_key).sum())

display(urban_greece[["OBS_FLAG", "Observation status (Flag) V2 structure"]].value_counts(dropna=False))

Available years: [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

      deg_urb Degree of urbanisation
258      DEG1                 Cities
16827    DEG2      Towns and suburbs
33033    DEG3            Rural areas

          age            Age class sex      Sex
258     TOTAL                Total   F  Females
1047   Y18-64  From 18 to 64 years   F  Females
1836   Y_GE18     18 years or over   F  Females
2625   Y_GE60     60 years or over   F  Females
3414   Y_GE65     65 years or over   F  Females
4203   Y_GE75     75 years or over   F  Females
4992   Y_LT18   Less than 18 years   F  Females
5781    TOTAL                Total   M    Males
6570   Y18-64  From 18 to 64 years   M    Males
7359   Y_GE18     18 years or over   M    Males
8148   Y_GE60     60 years or over   M    Males
8937   Y_GE65     65 years or over   M    Males
9726   Y_GE75     75 years or over   M    Males
10515  Y_LT18   Less than 18 years   M    Males
11304   TOTAL                Total   T    Total
12093  Y18-64  From 18 to 64 years   T    Total
12882  Y_GE18     18 years or over   T    Total
13671  Y_GE60     60 years or over   T    Total
14460  Y_GE65     65 years or over   T    Total
15249  Y_GE75     75 years or over   T    Total
16038  Y_LT18   Less than 18 years   T    Total

Column types:
TIME_PERIOD      int64
OBS_VALUE      float64
OBS_FLAG           str
dtype: object
Missing values: 132
Duplicate observation keys: 0

OBS_FLAG  Observation status (Flag) V2 structure
NaN       NaN                                       8082
b         break in time series                       378
u         low reliability                            210
Name: count, dtype: int64

In [101]:
# Keep the published groups and units separate.
urban_clean = urban_greece.loc[
    urban_greece["sex"] == "T",
    [
        "geo", "Geopolitical entity (reporting)", "TIME_PERIOD",
        "age", "Age class", "sex", "statinfo", "unit",
        "deg_urb", "Degree of urbanisation",
        "OBS_VALUE", "OBS_FLAG"
    ]].copy()

In [102]:
urban_clean = urban_clean.rename(columns={
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "statinfo": "indicator",
    "OBS_VALUE": "income",
    "OBS_FLAG": "obs_flag"})

In [103]:
urban_clean = urban_clean.sort_values(["unit", "indicator", "age", "deg_urb", "year"])

print("Prepared shape:", urban_clean.shape)
print("Missing values:", urban_clean["income"].isna().sum())

Prepared shape: (2898, 12)
Missing values: 42

In [104]:
# Identify the retained observations with missing income.
display(urban_clean.loc[urban_clean["income"].isna(), ["year", "age", "deg_urb", "indicator", "unit", "obs_flag"]])

        year     age deg_urb indicator unit obs_flag
29946   2004  Y_GE60    DEG2   MEAN_EI  EUR        u
29947   2005  Y_GE60    DEG2   MEAN_EI  EUR        u
30718   2004  Y_GE65    DEG2   MEAN_EI  EUR        u
30719   2005  Y_GE65    DEG2   MEAN_EI  EUR        u
31490   2004  Y_GE75    DEG2   MEAN_EI  EUR        u
31491   2005  Y_GE75    DEG2   MEAN_EI  EUR        u
32263   2005  Y_LT18    DEG2   MEAN_EI  EUR        u
79242   2004  Y_GE60    DEG2    MED_EI  EUR        u
79243   2005  Y_GE60    DEG2    MED_EI  EUR        u
80014   2004  Y_GE65    DEG2    MED_EI  EUR        u
80015   2005  Y_GE65    DEG2    MED_EI  EUR        u
80786   2004  Y_GE75    DEG2    MED_EI  EUR        u
80787   2005  Y_GE75    DEG2    MED_EI  EUR        u
81559   2005  Y_LT18    DEG2    MED_EI  EUR        u
125722  2004  Y_GE60    DEG2   MEAN_EI  NAC        u
125723  2005  Y_GE60    DEG2   MEAN_EI  NAC        u
126421  2004  Y_GE65    DEG2   MEAN_EI  NAC        u
126422  2005  Y_GE65    DEG2   MEAN_EI  NAC        u
127120  2004  Y_GE75    DEG2   MEAN_EI  NAC        u
127121  2005  Y_GE75    DEG2   MEAN_EI  NAC        u
127820  2005  Y_LT18    DEG2   MEAN_EI  NAC        u
170419  2004  Y_GE60    DEG2    MED_EI  NAC        u
170420  2005  Y_GE60    DEG2    MED_EI  NAC        u
171118  2004  Y_GE65    DEG2    MED_EI  NAC        u
171119  2005  Y_GE65    DEG2    MED_EI  NAC        u
171817  2004  Y_GE75    DEG2    MED_EI  NAC        u
171818  2005  Y_GE75    DEG2    MED_EI  NAC        u
172517  2005  Y_LT18    DEG2    MED_EI  NAC        u
217932  2004  Y_GE60    DEG2   MEAN_EI  PPS        u
217933  2005  Y_GE60    DEG2   MEAN_EI  PPS        u
218704  2004  Y_GE65    DEG2   MEAN_EI  PPS        u
218705  2005  Y_GE65    DEG2   MEAN_EI  PPS        u
219476  2004  Y_GE75    DEG2   MEAN_EI  PPS        u
219477  2005  Y_GE75    DEG2   MEAN_EI  PPS        u
220249  2005  Y_LT18    DEG2   MEAN_EI  PPS        u
267228  2004  Y_GE60    DEG2    MED_EI  PPS        u
267229  2005  Y_GE60    DEG2    MED_EI  PPS        u
268000  2004  Y_GE65    DEG2    MED_EI  PPS        u
268001  2005  Y_GE65    DEG2    MED_EI  PPS        u
268772  2004  Y_GE75    DEG2    MED_EI  PPS        u
268773  2005  Y_GE75    DEG2    MED_EI  PPS        u
269545  2005  Y_LT18    DEG2    MED_EI  PPS        u

In [105]:
# Summarise flagged observations by year.
display(urban_clean.loc[urban_clean["obs_flag"].notna()].groupby(["year", "obs_flag"]).size().reset_index(name="observations"))

   year obs_flag  observations
0  2004        u            24
1  2005        u            36
2  2012        b           126

In [106]:
# Preserve the original values, missingness and flags.
urban_clean.to_csv("../data/processed/ilc_di17_greece.csv", index=False, encoding="utf-8")

### Housing cost overburden across countries

We track the share of people whose household housing costs exceed 40% of disposable income. Both costs and income are net of housing allowances ([Eurostat definition](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Housing_cost_overburden_rate)).

In [107]:
housing_raw = pd.read_csv("../data/raw/ilc_lvho07a_linear_2_0.csv")

# Select the total population, keeping countries rather than EU/EA aggregates.
housing_europe = housing_raw.loc[
    (housing_raw["freq"] == "A")
    & (housing_raw["unit"] == "PC")
    & (housing_raw["age"] == "TOTAL")
    & (housing_raw["sex"] == "T")
    & (housing_raw["rskpovth"] == "TOTAL")
    & housing_raw["TIME_PERIOD"].between(2003, 2025)
    & ~housing_raw["geo"].str.startswith(("EU", "EA"))].copy()

display(
    housing_europe[
        ["STRUCTURE_ID", "freq", "unit", "age", "sex", "rskpovth"]
    ].drop_duplicates())

                 STRUCTURE_ID freq unit    age sex rskpovth
86148  ESTAT:ILC_LVHO07A(1.0)    A   PC  TOTAL   T    TOTAL

In [108]:
# Summarise coverage without filling values or excluding countries.
housing_coverage = (
    housing_europe.groupby(
        ["geo", "Geopolitical entity (reporting)"]
    )
    .agg(
        first_survey_year=("TIME_PERIOD", "min"),
        last_survey_year=("TIME_PERIOD", "max"),
        survey_years=("TIME_PERIOD", "nunique"),
        rows=("OBS_VALUE", "size"),
        non_missing_values=("OBS_VALUE", "count")
    )
    .reset_index()
    .sort_values("Geopolitical entity (reporting)"))

display(housing_coverage)

print("Missing values:", housing_europe["OBS_VALUE"].isna().sum())
print(
    "Duplicate country-year keys:",
    housing_europe.duplicated(["geo", "TIME_PERIOD"]).sum())

,geo,Geopolitical entity (reporting),first_survey_year,last_survey_year,survey_years,rows,non_missing_values
0,AL,Albania,2017,2025,9,9,9
1,AT,Austria,2004,2025,22,22,22
2,BE,Belgium,2004,2025,22,22,22
3,BG,Bulgaria,2006,2025,20,20,20
14,HR,Croatia,2010,2025,16,16,16
5,CY,Cyprus,2005,2025,21,21,21
6,CZ,Czechia,2005,2025,21,21,21
8,DK,Denmark,2005,2025,21,21,21
9,EE,Estonia,2005,2025,21,21,21
12,FI,Finland,2004,2025,22,22,22
13,FR,France,2004,2025,21,21,21
7,DE,Germany,2010,2025,16,16,16
10,EL,Greece,2004,2025,22,22,22
15,HU,Hungary,2005,2025,21,21,21
17,IS,Iceland,2004,2020,17,17,17
16,IE,Ireland,2003,2025,23,23,23
18,IT,Italy,2004,2025,22,22,22
36,XK,Kosovo*,2018,2018,1,1,1
21,LV,Latvia,2005,2025,21,21,21
19,LT,Lithuania,2005,2025,21,21,21
20,LU,Luxembourg,2003,2025,23,23,23
24,MT,Malta,2005,2025,21,21,21
22,ME,Montenegro,2013,2024,12,12,12
25,NL,Netherlands,2005,2025,21,21,21
23,MK,North Macedonia,2011,2024,14,14,14
26,NO,Norway,2004,2025,22,22,22
27,PL,Poland,2005,2025,21,21,21
28,PT,Portugal,2004,2025,22,22,22
29,RO,Romania,2007,2025,19,19,19
30,RS,Serbia,2013,2025,13,13,13
33,SK,Slovakia,2005,2025,21,21,21
32,SI,Slovenia,2005,2025,21,21,21
11,ES,Spain,2004,2025,22,22,22
31,SE,Sweden,2004,2025,22,22,22
4,CH,Switzerland,2009,2024,16,16,16
34,TR,Türkiye,2006,2025,20,20,20
35,UK,United Kingdom,2005,2018,14,14,14

Missing values: 0
Duplicate country-year keys: 0

In [109]:
# Inspect flags in the selected population before exporting.
display(
    housing_europe.loc[
        housing_europe["OBS_FLAG"].notna(),
        [
            "geo", "TIME_PERIOD", "OBS_VALUE", "OBS_FLAG",
            "Observation status (Flag) V2 structure"
        ]
    ].sort_values(["geo", "TIME_PERIOD"]))

,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,Observation status (Flag) V2 structure
86157,AT,2004,7.9,u,low reliability
86161,AT,2008,8.5,bu,"break in time series, low reliability"
86162,AT,2009,8.0,u,low reliability
86163,AT,2010,7.5,u,low reliability
86164,AT,2011,7.8,u,low reliability
86194,BE,2019,8.4,b,break in time series
86211,BG,2016,20.7,b,break in time series
86226,CH,2014,11.7,b,break in time series
86240,CY,2008,1.8,b,break in time series
86289,DE,2020,9.0,b,break in time series
86292,DE,2023,13.0,b,break in time series
86301,DK,2011,18.5,b,break in time series
86310,DK,2020,14.1,b,break in time series
86315,DK,2025,14.7,b,break in time series
86398,EE,2014,8.3,b,break in time series
86436,ES,2008,9.4,b,break in time series
86546,FR,2020,5.6,b,break in time series
86547,FR,2022,6.5,b,break in time series
86581,HU,2019,3.9,b,break in time series
86604,IE,2019,5.2,b,break in time series
86605,IE,2020,4.2,b,break in time series
86669,LT,2024,6.2,p,provisional
86670,LT,2025,5.7,p,provisional
86684,LU,2016,7.0,b,break in time series
86688,LU,2020,8.5,b,break in time series
86689,LU,2021,5.1,b,break in time series
86690,LU,2022,9.0,b,break in time series
86691,LU,2023,11.5,b,break in time series
86693,LU,2025,8.1,b,break in time series
86737,MK,2021,7.8,b,break in time series
86759,MT,2023,6.0,b,break in time series
86773,NL,2016,10.7,b,break in time series
86800,NO,2021,10.9,b,break in time series
86820,PL,2020,4.9,b,break in time series
86884,SE,2008,10.0,b,break in time series
86943,SK,2025,3.5,b,break in time series
86971,UK,2012,7.3,b,break in time series
86973,UK,2014,12.5,b,break in time series
86976,UK,2017,12.4,b,break in time series

In [110]:
housing_europe_clean = housing_europe[
    [
        "geo", "Geopolitical entity (reporting)", "TIME_PERIOD",
        "freq", "unit", "age", "sex", "rskpovth",
        "OBS_VALUE", "OBS_FLAG",
        "Observation status (Flag) V2 structure"]].copy()

housing_europe_clean = housing_europe_clean.rename(columns={
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "housing_overburden_rate",
    "OBS_FLAG": "obs_flag",
    "Observation status (Flag) V2 structure": "flag_description"}).sort_values(["geo_name", "year"])

housing_europe_clean.to_csv("../data/processed/ilc_lvho07a_europe.csv",index=False)

display(housing_europe_clean.head())

,geo_code,geo_name,year,freq,unit,age,sex,rskpovth,housing_overburden_rate,obs_flag,flag_description
86148,AL,Albania,2017,A,PC,TOTAL,T,TOTAL,9.2,NaN,NaN
86149,AL,Albania,2018,A,PC,TOTAL,T,TOTAL,6.0,NaN,NaN
86150,AL,Albania,2019,A,PC,TOTAL,T,TOTAL,5.5,NaN,NaN
86151,AL,Albania,2020,A,PC,TOTAL,T,TOTAL,3.8,NaN,NaN
86152,AL,Albania,2021,A,PC,TOTAL,T,TOTAL,3.3,NaN,NaN

In [111]:
# Retain both published income groups, all ages and sexes.
# Rates refer to people within each income group.
housing_income_europe = housing_raw.loc[
    (housing_raw["freq"] == "A")
    & (housing_raw["unit"] == "PC")
    & (housing_raw["age"] == "TOTAL")
    & (housing_raw["sex"] == "T")
    & housing_raw["rskpovth"].isin(["B_60", "A_60"])
    & housing_raw["TIME_PERIOD"].between(2003, 2025)
    & ~housing_raw["geo"].str.startswith(("EU", "EA")),
    [
        "geo", "Geopolitical entity (reporting)", "TIME_PERIOD",
        "freq", "unit", "age", "sex",
        "rskpovth", "Risk of poverty threshold",
        "OBS_VALUE", "OBS_FLAG",
        "Observation status (Flag) V2 structure"]].copy()

housing_income_europe = housing_income_europe.rename(columns={
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "year",
    "Risk of poverty threshold": "income_group_label",
    "OBS_VALUE": "housing_overburden_rate",
    "OBS_FLAG": "obs_flag",
    "Observation status (Flag) V2 structure": "flag_description"
}).sort_values(["geo_name", "rskpovth", "year"])

housing_income_key = ["geo_code", "year", "rskpovth"]

print("Prepared shape:", housing_income_europe.shape)
print(
    "Duplicate observation keys:",
    housing_income_europe.duplicated(housing_income_key).sum())
print(
    "Missing values:",
    housing_income_europe["housing_overburden_rate"].isna().sum())

display(
    housing_income_europe[
        ["freq", "unit", "age", "sex", "rskpovth", "income_group_label"]
    ].drop_duplicates().sort_values("rskpovth"))

Prepared shape: (1408, 12)
Duplicate observation keys: 0
Missing values: 0

      freq unit    age sex rskpovth income_group_label
1662     A   PC  TOTAL   T     A_60          Above 60%
43905    A   PC  TOTAL   T     B_60          Below 60%

In [112]:
housing_income_2024 = housing_income_europe.loc[housing_income_europe["year"] == 2024].copy()

housing_group_countries = (
    housing_europe_clean[["geo_code", "geo_name"]]
    .drop_duplicates()
    .sort_values("geo_name")
    .set_index("geo_code"))

# Reindex to retain every country and both groups, including absent observations.
housing_group_values_2024 = housing_income_2024.pivot(
    index="geo_code",
    columns="rskpovth",
    values="housing_overburden_rate"
).reindex(
    index=housing_group_countries.index,
    columns=["B_60", "A_60"])

housing_group_coverage_2024 = housing_group_countries.join(
    housing_group_values_2024)

housing_group_coverage_2024["both_available"] = (
    housing_group_coverage_2024[["B_60", "A_60"]]
    .notna()
    .all(axis=1))

print("2024 coverage and housing cost overburden rates (%):")
display(housing_group_coverage_2024)

print("2024 flagged observations:")
display(
    housing_income_2024.loc[
        housing_income_2024["obs_flag"].notna(),
        [
            "geo_code", "geo_name", "rskpovth",
            "housing_overburden_rate", "obs_flag", "flag_description"]])

2024 coverage and housing cost overburden rates (%):

                 geo_name  B_60  A_60  both_available
geo_code
AL                Albania   8.8   0.8            True
AT                Austria  35.5   1.4            True
BE                Belgium  33.3   3.3            True
BG               Bulgaria  29.4   2.1            True
HR                Croatia  16.8   0.3            True
CY                 Cyprus   9.2   1.2            True
CZ                Czechia  47.4   5.2            True
DK                Denmark  65.6   7.8            True
EE                Estonia  29.6   3.3            True
FI                Finland  22.4   3.0            True
FR                 France  27.9   3.0            True
DE                Germany  37.5   7.3            True
EL                 Greece  88.9  14.2            True
HU                Hungary  34.2   4.8            True
IS                Iceland   NaN   NaN           False
IE                Ireland  17.0   2.7            True
IT                  Italy  21.8   1.2            True
XK                Kosovo*   NaN   NaN           False
LV                 Latvia  25.7   1.5            True
LT              Lithuania  22.5   1.7            True
LU             Luxembourg  29.0   4.0            True
MT                  Malta  25.3   1.9            True
ME             Montenegro  30.3   3.4            True
NL            Netherlands  27.9   3.9            True
MK        North Macedonia  24.6   0.3            True
NO                 Norway  52.3  10.6            True
PL                 Poland  26.2   1.8            True
PT               Portugal  25.9   3.1            True
RO                Romania  16.3   2.0            True
RS                 Serbia  46.8   2.8            True
SK               Slovakia  35.5   1.5            True
SI               Slovenia  20.6   1.3            True
ES                  Spain  29.9   2.4            True
SE                 Sweden  47.7   4.3            True
CH            Switzerland  56.1   7.4            True
TR                Türkiye  26.5  11.5            True
UK         United Kingdom   NaN   NaN           False

2024 flagged observations:

,geo_code,geo_name,rskpovth,housing_overburden_rate,obs_flag,flag_description
2183,LT,Lithuania,A_60,1.7,p,provisional
44426,LT,Lithuania,B_60,22.5,p,provisional

In [113]:
# Preserve all years, missing values and source flags.
housing_income_europe.to_csv("../data/processed/ilc_lvho07a_europe_income_groups.csv", index=False)

print("Saved:", housing_income_europe.shape)

Saved: (1408, 12)

### HICP

In [114]:
# Retain EUR and NAC separately for the currency-unit review.
income_for_real = pd.read_csv("../data/processed/ilc_di03_clean.csv")

median_europe_units = income_for_real.loc[
    (income_for_real["age"] == "TOTAL")
    & (income_for_real["sex"] == "T")
    & (income_for_real["indicator"] == "MED_EI")
    & income_for_real["unit"].isin(["EUR", "NAC"])
    & income_for_real["year"].between(2003, 2025)
    & ~income_for_real["geo_code"].str.startswith(("EU", "EA")),
    [
        "geo_code", "geo_name", "year", "unit", "income",
        "obs_flag", "Observation status (Flag) V2 structure"
    ]].copy()

real_country_names = (
    median_europe_units[["geo_code", "geo_name"]]
    .drop_duplicates()
    .set_index("geo_code")["geo_name"]
    .sort_values())

hicp_europe_raw = pd.read_csv("../data/raw/prc_hicp_ainr__custom_23673998_linear_2_0.csv")

In [115]:
# Select the annual average all-items index, keeping all available years.
hicp_europe = hicp_europe_raw.loc[
    (hicp_europe_raw["freq"] == "A")
    & (hicp_europe_raw["unit"] == "INX_A_AVG")
    & (hicp_europe_raw["coicop18"] == "TOTAL")
    & hicp_europe_raw["geo"].isin(real_country_names.index),
    [
        "geo", "Geopolitical entity (reporting)", "TIME_PERIOD",
        "freq", "unit", "coicop18", "OBS_VALUE", "OBS_FLAG",
        "Observation status (Flag) V2 structure"
    ]].copy()

hicp_europe = hicp_europe.rename(columns={
    "geo": "geo_code",
    "Geopolitical entity (reporting)": "geo_name",
    "TIME_PERIOD": "price_year",
    "OBS_VALUE": "hicp",
    "OBS_FLAG": "hicp_flag",
    "Observation status (Flag) V2 structure": "hicp_flag_description"
}).sort_values(["geo_name", "price_year"])

print("Prepared HICP shape:", hicp_europe.shape)
print(
    "Duplicate HICP keys:",
    hicp_europe.duplicated(["geo_code", "price_year"]).sum())
print("Missing HICP values:", hicp_europe["hicp"].isna().sum())

print(
    "Duplicate income keys:",
    median_europe_units.duplicated(["geo_code", "year", "unit"]).sum())

display(hicp_europe[["freq", "unit", "coicop18"]].drop_duplicates())

Prepared HICP shape: (989, 9)
Duplicate HICP keys: 0
Missing HICP values: 0
Duplicate income keys: 0

  freq       unit coicop18
0    A  INX_A_AVG    TOTAL

In [116]:
median_nac_europe = median_europe_units.loc[median_europe_units["unit"] == "NAC"].copy()

income_coverage = median_nac_europe.groupby("geo_code").agg(
    first_survey_year=("year", "min"),
    last_survey_year=("year", "max"),
    survey_years=("year", "nunique"),
    income_values=("income", "count"))

hicp_coverage = hicp_europe.groupby("geo_code").agg(
    first_price_year=("price_year", "min"),
    last_price_year=("price_year", "max"),
    price_years=("price_year", "nunique"),
    hicp_values=("hicp", "count"))

real_data_coverage = (
    real_country_names.to_frame()
    .join(income_coverage)
    .join(hicp_coverage))

print("Income and HICP coverage:")
display(real_data_coverage)

print("Flagged HICP observations:")
display(
    hicp_europe.loc[
        hicp_europe["hicp_flag"].notna(),
        [
            "geo_name", "price_year", "hicp",
            "hicp_flag", "hicp_flag_description"
        ]])

print("Flagged NAC income observations:")
display(
    median_nac_europe.loc[
        median_nac_europe["obs_flag"].notna(),
        [
            "geo_name", "year", "income", "obs_flag",
            "Observation status (Flag) V2 structure"
        ]
    ].sort_values(["geo_name", "year"]))

Income and HICP coverage:

,geo_name,first_survey_year,last_survey_year,survey_years,income_values,first_price_year,last_price_year,price_years,hicp_values
geo_code,,,,,,,,,
AL,Albania,2017,2025,9,9,2016,2025,10,10
AT,Austria,2003,2025,23,23,1996,2025,30,30
BE,Belgium,2003,2025,23,23,1996,2025,30,30
BG,Bulgaria,2006,2025,20,20,1997,2025,29,29
HR,Croatia,2010,2025,16,16,1998,2025,28,28
CY,Cyprus,2005,2025,21,21,1996,2025,30,30
CZ,Czechia,2005,2025,21,21,1996,2025,30,30
DK,Denmark,2003,2025,23,23,1996,2025,30,30
EE,Estonia,2004,2025,22,22,1996,2025,30,30
FI,Finland,2004,2025,22,22,1996,2025,30,30
FR,France,2004,2025,22,22,1996,2025,30,30
DE,Germany,2005,2025,21,21,1996,2025,30,30
EL,Greece,2003,2025,23,23,1996,2025,30,30
HU,Hungary,2005,2025,21,21,1996,2025,30,30
IS,Iceland,2004,2020,17,17,2016,2025,10,10
IE,Ireland,2003,2025,23,23,1996,2025,30,30
IT,Italy,2004,2025,22,22,1996,2025,30,30
XK,Kosovo*,2018,2018,1,1,2015,2025,11,11
LV,Latvia,2005,2025,21,21,1996,2025,30,30
LT,Lithuania,2005,2025,21,21,1996,2025,30,30
LU,Luxembourg,2003,2025,23,23,1996,2025,30,30
MT,Malta,2005,2025,21,21,1996,2025,30,30
ME,Montenegro,2013,2024,12,12,2015,2025,11,11
NL,Netherlands,2005,2025,21,21,1996,2025,30,30
MK,North Macedonia,2012,2024,13,13,2005,2025,21,21
NO,Norway,2003,2025,23,23,2000,2025,26,26
PL,Poland,2005,2025,21,21,1996,2025,30,30
PT,Portugal,2004,2025,22,22,1996,2025,30,30
RO,Romania,2007,2025,19,19,1996,2025,30,30
RS,Serbia,2013,2025,13,13,2006,2025,20,20
SK,Slovakia,2005,2025,21,21,1997,2025,29,29
SI,Slovenia,2005,2025,21,21,1996,2025,30,30
ES,Spain,2004,2025,22,22,1996,2025,30,30
SE,Sweden,2004,2025,22,22,1996,2025,30,30
CH,Switzerland,2007,2024,18,18,2005,2025,21,21
TR,Türkiye,2006,2025,20,20,1996,2025,30,30
UK,United Kingdom,2005,2018,14,14,1997,2019,23,23

Flagged HICP observations:

Empty DataFrame
Columns: [geo_name, price_year, hicp, hicp_flag, hicp_flag_description]
Index: []

Flagged NAC income observations:

,geo_name,year,income,obs_flag,Observation status (Flag) V2 structure
3162,Austria,2003,15630,b,break in time series
3167,Austria,2008,19413,b,break in time series
3185,Belgium,2003,15522,b,break in time series
3201,Belgium,2019,24654,b,break in time series
3218,Bulgaria,2016,6163,b,break in time series
3456,Croatia,2023,9873,b,break in time series
3457,Croatia,2024,12344,b,break in time series
3249,Cyprus,2008,9336,b,break in time series
3317,Denmark,2011,200663,b,break in time series
3326,Denmark,2020,229067,b,break in time series
3342,Estonia,2014,7217,b,break in time series
3399,Finland,2004,16679,b,break in time series
3421,France,2004,15242,b,break in time series
3425,France,2008,18899,b,break in time series
3437,France,2020,22143,b,break in time series
3439,France,2022,23053,b,break in time series
3288,Germany,2005,16393,b,break in time series
3303,Germany,2020,26008,b,break in time series
3354,Greece,2003,8206,b,break in time series
3473,Hungary,2019,1862960,b,break in time series
3480,Ireland,2003,17079,b,break in time series
3496,Ireland,2019,25422,b,break in time series
3497,Ireland,2020,26766,b,break in time series
3520,Italy,2004,13631,b,break in time series
3561,Lithuania,2024,12325,p,provisional
3562,Lithuania,2025,13982,p,provisional
3563,Luxembourg,2003,25780,b,break in time series
3576,Luxembourg,2016,32841,b,break in time series
3580,Luxembourg,2020,37844,b,break in time series
3581,Luxembourg,2021,42482,b,break in time series
3582,Luxembourg,2022,45310,b,break in time series
3585,Luxembourg,2025,50046,b,break in time series
3653,Netherlands,2005,17000,b,break in time series
3664,Netherlands,2016,22733,b,break in time series
3628,North Macedonia,2021,198714,b,break in time series
3692,Norway,2021,385069,b,break in time series
3694,Norway,2023,422434,b,break in time series
3718,Portugal,2004,6916,b,break in time series
3835,Slovakia,2025,12990,b,break in time series
3377,Spain,2004,10327,b,break in time series
3381,Spain,2008,13966,b,break in time series
3776,Sweden,2008,187007,b,break in time series
3235,Switzerland,2014,46982,b,break in time series
3856,United Kingdom,2005,12678,b,break in time series
3863,United Kingdom,2012,15541,b,break in time series
3868,United Kingdom,2017,18406,b,break in time series

In [117]:
currency_unit_check = median_europe_units.pivot(
    index=["geo_code", "geo_name", "year"],
    columns="unit",
    values="income"
).reindex(columns=["EUR", "NAC"])

# Compare only records with both published values available.
currency_unit_check = (
    currency_unit_check
    .dropna(subset=["EUR", "NAC"])
    .reset_index())

currency_unit_check["nac_equals_eur"] = (currency_unit_check["NAC"] == currency_unit_check["EUR"])

currency_unit_summary = (
    currency_unit_check
    .groupby(["geo_code", "geo_name", "nac_equals_eur"])
    .agg(
        first_survey_year=("year", "min"),
        last_survey_year=("year", "max"),
        observations=("year", "nunique")
    )
    .reset_index()
    .sort_values(["geo_name", "first_survey_year"]))

display(currency_unit_summary)

,geo_code,geo_name,nac_equals_eur,first_survey_year,last_survey_year,observations
0,AL,Albania,False,2017,2025,9
1,AT,Austria,True,2003,2025,23
2,BE,Belgium,True,2003,2025,23
3,BG,Bulgaria,False,2006,2025,20
15,HR,Croatia,False,2010,2022,13
16,HR,Croatia,True,2023,2025,3
5,CY,Cyprus,False,2005,2008,4
6,CY,Cyprus,True,2009,2025,17
7,CZ,Czechia,False,2005,2025,21
9,DK,Denmark,False,2003,2025,23
10,EE,Estonia,True,2004,2025,22
13,FI,Finland,True,2004,2025,22
14,FR,France,True,2004,2025,22
8,DE,Germany,True,2005,2025,21
11,EL,Greece,True,2003,2025,23
17,HU,Hungary,False,2005,2025,21
19,IS,Iceland,False,2004,2020,17
18,IE,Ireland,True,2003,2025,23
20,IT,Italy,True,2004,2025,22
42,XK,Kosovo*,True,2018,2018,1
24,LV,Latvia,True,2005,2025,21
21,LT,Lithuania,False,2005,2014,10
22,LT,Lithuania,True,2015,2025,11
23,LU,Luxembourg,True,2003,2025,23
27,MT,Malta,False,2005,2006,2
28,MT,Malta,True,2007,2025,19
25,ME,Montenegro,True,2013,2024,12
29,NL,Netherlands,True,2005,2025,21
26,MK,North Macedonia,False,2012,2024,13
30,NO,Norway,False,2003,2025,23
31,PL,Poland,False,2005,2025,21
32,PT,Portugal,True,2004,2025,22
33,RO,Romania,False,2007,2025,19
34,RS,Serbia,False,2013,2025,13
38,SK,Slovakia,False,2005,2008,4
39,SK,Slovakia,True,2009,2025,17
36,SI,Slovenia,False,2005,2006,2
37,SI,Slovenia,True,2007,2025,19
12,ES,Spain,True,2004,2025,22
35,SE,Sweden,False,2004,2025,22
4,CH,Switzerland,False,2007,2024,18
40,TR,Türkiye,False,2006,2025,20
41,UK,United Kingdom,False,2005,2018,14

In [118]:
# Preserve all available years, missing values and source flags.
hicp_europe.to_csv("../data/processed/hicp_europe.csv", index=False)

print("Saved:", hicp_europe.shape)

Saved: (989, 9)

In [119]:
# This preparation is specific to income years 2019–2023.
real_income_input = median_europe_units.loc[
    (median_europe_units["unit"] == "NAC")
    & median_europe_units["year"].between(2020, 2024)].copy()

real_income_input = real_income_input.rename(columns={
    "year": "survey_year",
    "income": "income_nac",
    "obs_flag": "income_flag",
    "Observation status (Flag) V2 structure": "income_flag_description"})

In [120]:
# These survey years use the previous calendar year as the income reference period.
real_income_input["income_year"] = (real_income_input["survey_year"] - 1)
real_income_input["currency_divisor"] = 1.0
real_income_input["analysis_unit"] = "NAC"

In [121]:
# In the original export, Croatian NAC values use kuna through survey year 2022.
# Fixed conversion source:
# https://www.ecb.europa.eu/euro/changeover/croatia/html/index.en.html
legacy_kuna = ((real_income_input["geo_code"] == "HR") & (real_income_input["survey_year"] <= 2022))

real_income_input.loc[legacy_kuna, "currency_divisor"] = 7.53450
real_income_input.loc[real_income_input["geo_code"] == "HR", "analysis_unit"] = "EUR"

real_income_input["income_for_deflation"] = (real_income_input["income_nac"] / real_income_input["currency_divisor"])

print("Croatian currency adjustment:")
display(
    real_income_input.loc[
        real_income_input["geo_code"] == "HR",
        [
            "survey_year", "income_year", "income_nac",
            "currency_divisor", "income_for_deflation", "analysis_unit"
        ]].sort_values("income_year"))

real_income_input.to_csv("../data/processed/ilc_di03_real_input_2019_2023.csv", index=False)

print("Saved:", real_income_input.shape)

Croatian currency adjustment:

,survey_year,income_year,income_nac,currency_divisor,income_for_deflation,analysis_unit
3453,2020,2019,58541,7.5345,7769.725927,EUR
3454,2021,2020,60768,7.5345,8065.299622,EUR
3455,2022,2021,66000,7.5345,8759.705355,EUR
3456,2023,2022,9873,1.0000,9873.000000,EUR
3457,2024,2023,12344,1.0000,12344.000000,EUR

Saved: (171, 11)